2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Configure stats pid to 48304
2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Loading settings from C:\Users\10515\.config\wandb\settings
2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Loading settings from C:\Users\10515\Desktop\examine\Grab-cut\wandb\settings
2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-15 22:28:04,634 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-15 22:28:04,635 INFO    MainThread:48304 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'metrics.py', 'program': 'C:/Users/10515/Desktop/examine/Grab-cut/metrics.py'}
2023-07-15 22:28:04,635 INFO    MainThread:48304 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\logs\debug.log
2023-07-15 22:28:04,635 INFO    MainThread:48304 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\logs\debug-internal.log
2023-07-15 22:28:04,635 INFO    MainThread:48304 [wandb_init.py:init():547] calling init triggers
2023-07-15 22:28:04,635 INFO    MainThread:48304 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-07-15 22:28:04,636 INFO    MainThread:48304 [wandb_init.py:init():596] starting backend
2023-07-15 22:28:04,636 INFO    MainThread:48304 [wandb_init.py:init():600] setting up manager
2023-07-15 22:28:04,640 INFO    MainThread:48304 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-07-15 22:28:04,646 INFO    MainThread:48304 [wandb_init.py:init():606] backend started and connected
2023-07-15 22:28:04,647 INFO    MainThread:48304 [wandb_init.py:init():703] updated telemetry
2023-07-15 22:28:04,656 INFO    MainThread:48304 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-07-15 22:28:05,428 INFO    MainThread:48304 [wandb_run.py:_on_init():2176] communicating current version
2023-07-15 22:28:06,461 INFO    MainThread:48304 [wandb_run.py:_on_init():2185] got version response upgrade_message: "wandb version 0.15.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-07-15 22:28:06,461 INFO    MainThread:48304 [wandb_init.py:init():787] starting run threads in backend
2023-07-15 22:28:22,598 WARNING MsgRouterThr:48304 [router.py:message_loop():77] message_loop has been closed
2023-07-15 22:28:27,441 ERROR   MainThread:48304 [wandb_init.py:init():1170] transport failed
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1152, in init
    run = wi.init()
  File "D:\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 798, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "D:\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
