2023-07-15 22:28:04,645 INFO    StreamThr :42468 [internal.py:wandb_internal():89] W&B internal server running at pid: 42468, started at: 2023-07-15 22:28:04.644583
2023-07-15 22:28:04,648 DEBUG   HandlerThread:42468 [handler.py:handle_request():144] handle_request: status
2023-07-15 22:28:04,650 INFO    WriterThread:42468 [datastore.py:open_for_write():85] open: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\run-n6tzr2cl.wandb
2023-07-15 22:28:04,657 DEBUG   SenderThread:42468 [sender.py:send():369] send: header
2023-07-15 22:28:04,657 DEBUG   SenderThread:42468 [sender.py:send():369] send: run
2023-07-15 22:28:05,418 INFO    SenderThread:42468 [dir_watcher.py:__init__():211] watching files in: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files
2023-07-15 22:28:05,418 INFO    SenderThread:42468 [sender.py:_start_run_threads():1103] run started: n6tzr2cl with start time 1689431284.647579
2023-07-15 22:28:05,418 DEBUG   SenderThread:42468 [sender.py:send_request():396] send_request: summary_record
2023-07-15 22:28:05,419 INFO    SenderThread:42468 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-15 22:28:05,429 DEBUG   HandlerThread:42468 [handler.py:handle_request():144] handle_request: check_version
2023-07-15 22:28:05,429 DEBUG   SenderThread:42468 [sender.py:send_request():396] send_request: check_version
2023-07-15 22:28:06,428 INFO    Thread-16 :42468 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-summary.json
2023-07-15 22:28:06,474 DEBUG   HandlerThread:42468 [handler.py:handle_request():144] handle_request: run_start
2023-07-15 22:28:06,597 DEBUG   HandlerThread:42468 [system_info.py:__init__():31] System info init
2023-07-15 22:28:06,597 DEBUG   HandlerThread:42468 [system_info.py:__init__():46] System info init done
2023-07-15 22:28:06,597 INFO    HandlerThread:42468 [system_monitor.py:start():181] Starting system monitor
2023-07-15 22:28:06,598 INFO    SystemMonitor:42468 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-15 22:28:06,598 INFO    HandlerThread:42468 [system_monitor.py:probe():201] Collecting system info
2023-07-15 22:28:06,605 INFO    SystemMonitor:42468 [interfaces.py:start():190] Started cpu monitoring
2023-07-15 22:28:06,606 INFO    SystemMonitor:42468 [interfaces.py:start():190] Started disk monitoring
2023-07-15 22:28:06,606 INFO    SystemMonitor:42468 [interfaces.py:start():190] Started gpu monitoring
2023-07-15 22:28:06,607 INFO    SystemMonitor:42468 [interfaces.py:start():190] Started memory monitoring
2023-07-15 22:28:06,642 INFO    SystemMonitor:42468 [interfaces.py:start():190] Started network monitoring
2023-07-15 22:28:06,663 DEBUG   HandlerThread:42468 [system_info.py:probe():195] Probing system
2023-07-15 22:28:06,668 DEBUG   HandlerThread:42468 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-15 22:28:06,668 DEBUG   HandlerThread:42468 [system_info.py:probe():240] Probing system done
2023-07-15 22:28:06,668 DEBUG   HandlerThread:42468 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.7.7', 'heartbeatAt': '2023-07-15T14:28:06.663326', 'startedAt': '2023-07-15T14:28:04.628786', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'C:/Users/10515/Desktop/examine/Grab-cut/metrics.py', 'codePath': 'metrics.py', 'host': 'LAPTOP-G4GJ76I2', 'username': '10515', 'executable': 'D:\\anaconda3\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2592.0, 'min': 0.0, 'max': 2592.0}, 'cpu_freq_per_core': [{'current': 2592.0, 'min': 0.0, 'max': 2592.0}], 'disk': {'total': 199.99316024780273, 'used': 181.4309959411621}, 'gpu': 'NVIDIA GeForce GTX 1650', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650', 'memory_total': 4294967296}], 'memory': {'total': 15.882068634033203}}
2023-07-15 22:28:06,668 INFO    HandlerThread:42468 [system_monitor.py:probe():211] Finished collecting system info
2023-07-15 22:28:06,669 INFO    HandlerThread:42468 [system_monitor.py:probe():214] Publishing system info
2023-07-15 22:28:06,669 DEBUG   HandlerThread:42468 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-07-15 22:28:06,671 DEBUG   HandlerThread:42468 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-15 22:28:06,671 DEBUG   HandlerThread:42468 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-07-15 22:28:06,684 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:07,432 INFO    Thread-16 :42468 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\requirements.txt
2023-07-15 22:28:07,432 INFO    Thread-16 :42468 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\conda-environment.yaml
2023-07-15 22:28:08,722 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:10,755 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:12,805 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:14,844 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:16,874 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:18,410 DEBUG   HandlerThread:42468 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-15 22:28:18,411 INFO    HandlerThread:42468 [system_monitor.py:probe():216] Finished publishing system info
2023-07-15 22:28:18,534 INFO    WriterThread:42468 [datastore.py:close():298] close: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\run-n6tzr2cl.wandb
2023-07-15 22:28:18,535 INFO    Thread-16 :42468 [dir_watcher.py:_on_file_modified():289] file/dir modified: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\conda-environment.yaml
2023-07-15 22:28:18,536 INFO    Thread-16 :42468 [dir_watcher.py:_on_file_created():272] file/dir created: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-metadata.json
2023-07-15 22:28:18,564 INFO    SenderThread:42468 [sender.py:finish():1526] shutting down sender
2023-07-15 22:28:18,565 INFO    SenderThread:42468 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-15 22:28:18,914 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:19,550 INFO    SenderThread:42468 [dir_watcher.py:finish():389] scan: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files
2023-07-15 22:28:19,551 INFO    SenderThread:42468 [dir_watcher.py:finish():403] scan save: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\conda-environment.yaml conda-environment.yaml
2023-07-15 22:28:19,552 INFO    SenderThread:42468 [dir_watcher.py:finish():403] scan save: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\config.yaml config.yaml
2023-07-15 22:28:19,555 INFO    SenderThread:42468 [dir_watcher.py:finish():403] scan save: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\requirements.txt requirements.txt
2023-07-15 22:28:19,560 INFO    SenderThread:42468 [dir_watcher.py:finish():403] scan save: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-metadata.json wandb-metadata.json
2023-07-15 22:28:19,565 INFO    SenderThread:42468 [dir_watcher.py:finish():403] scan save: C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-summary.json wandb-summary.json
2023-07-15 22:28:19,568 INFO    SenderThread:42468 [file_pusher.py:finish():159] shutting down file pusher
2023-07-15 22:28:19,569 INFO    SenderThread:42468 [file_pusher.py:join():164] waiting for file pusher
2023-07-15 22:28:20,370 INFO    wandb-upload_0:42468 [upload_job.py:push():133] Uploaded file C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\conda-environment.yaml
2023-07-15 22:28:20,485 INFO    wandb-upload_1:42468 [upload_job.py:push():133] Uploaded file C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\config.yaml
2023-07-15 22:28:20,502 INFO    wandb-upload_3:42468 [upload_job.py:push():133] Uploaded file C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-metadata.json
2023-07-15 22:28:20,508 INFO    wandb-upload_2:42468 [upload_job.py:push():133] Uploaded file C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\requirements.txt
2023-07-15 22:28:20,509 INFO    wandb-upload_4:42468 [upload_job.py:push():133] Uploaded file C:\Users\10515\Desktop\examine\Grab-cut\wandb\run-20230715_222804-n6tzr2cl\files\wandb-summary.json
2023-07-15 22:28:20,950 ERROR   gpu       :42468 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-07-15 22:28:22,295 ERROR   StreamThr :42468 [internal.py:wandb_internal():174] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\internal_util.py", line 100, in _run
    self._process(record)
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\internal.py", line 279, in _process
    self._hm.handle(record)
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\handler.py", line 136, in handle
    handler(record)
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\handler.py", line 146, in handle_request
    handler(record)
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\handler.py", line 709, in handle_request_run_start
    self._settings, interface=self._interface, run_proto=run_start.run
  File "D:\anaconda3\lib\site-packages\wandb\sdk\internal\tb_watcher.py", line 126, in __init__
    wandb.tensorboard.reset_state()
  File "D:\anaconda3\lib\site-packages\wandb\sdk\lib\lazyloader.py", line 58, in __getattr__
    module = self._load()
  File "D:\anaconda3\lib\site-packages\wandb\sdk\lib\lazyloader.py", line 33, in _load
    module = importlib.import_module(self.__name__)
  File "D:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\anaconda3\lib\site-packages\wandb\integration\tensorboard\__init__.py", line 3, in <module>
    from .log import _log, log, reset_state, tf_summary_to_dict  # noqa: F401
  File "D:\anaconda3\lib\site-packages\wandb\integration\tensorboard\log.py", line 35, in <module>
    Summary = pb.Summary if pb else None
  File "D:\anaconda3\lib\importlib\util.py", line 245, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "D:\anaconda3\lib\site-packages\tensorboard\compat\proto\summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import histogram_pb2 as tensorboard_dot_compat_dot_proto_dot_histogram__pb2
  File "D:\anaconda3\lib\site-packages\tensorboard\compat\proto\histogram_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "D:\anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
